- name: create user account managed1 
  hosts: managed1_host_diofathurr
  become: true

  vars_files:
    - secret.yml
    - group_vars/managed1-host-diofathurr.yml
  tasks:
    - name: Creating user ops1-50
      user: 
        name: "{{item}}"
        password: "{{pass | password_hash('sha512')}}"
      loop: "{{list_user_ops_managed1}}"
    
    - name: Creating user dev1-50
      user: 
        name: "{{item}}"
        password: "{{pass | password_hash('sha512')}}"
      loop: "{{list_user_dev_managed1}}"


- name: create user account managed2
  hosts: managed2_host_diofathurr
  become: true

  vars_files:
    - secret.yml
    - group_vars/managed2-host-diofathurr.yml
  tasks: 
    - name: Creating user ops51-100
      user: 
        name: "{{item}}"
        password: "{{pass | password_hash('sha512')}}"
      loop: "{{list_user_ops_managed2}}"
    
    - name: Creating user dev51-100
      user:
        name: "{{item}}"
        password: "{{pass | password_hash('sha512')}}"
      loop: "{{list_user_dev_managed2}}" 